[package]
name = "demultiplex"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
seq_io = "*"
bio = "*"
rayon = "*"
serde = { version = "*", features = ["derive"] }
csv = "*"
flate2 = "*"
anyhow = "*"
num_cpus = "*"
